### PR TITLE
Add smoke tests

### PR DESCRIPTION
**Pull request by ErikSchierboom**
This PR adds smoke tests for some common scenarios.

The goal of the smoke tests is to increase confidence that the Docker image that is produced works as 
intended.
The repo contains other tests, which are great, but what this PR adds is that it runs an integration 
test using the following setup:

1. Build the Docker image
2. Run the Docker image with the `tests` directory mapped into the container
3. Run the Docker image's normal entrypoint (`bin/run.sh`) on each of the test cases defined in the 
`tests` directory
4. Verify that the output of those test runs matches the expected output (which is stored inside the 
`tests` directories

If successful, we then know that:

1. The Docker image can be built successfully
2. The `bin/run.sh` entrypoint inside the Docker image is setup correctly
3. The test runner generates the correct output

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@NobbZ I found two things while working on this:

1. The test runner seems to crash when the input is an empty file or has a syntax error. Is that intentional? Most tracks will still return a `results.json` file but with a top-level status of `error` in that case, with `message` containing any relevant output (usually stdout). The main benefit of doing it like that is that the student can actually see the error message. Right now, the student will just see this generic message:

Screenshot 2023-08-11 at 13 31 44

2. The ordering of the tests seems to be random, which is perfectly fine but it will require me to do some JQ magic in order to get the `diff` approach that we use to compare the files working. Another option would be to order the tests by name, that way the interface is stable. The second option has my preference. What do you think?

**Comment by NobbZ** [comment]
1. I am aware of that, but forgot to create an issue about this.
2. I will have to check on that, I thought that test results are emitted in order of appearance in code.

**Comment by NobbZ** [comment]
1. I opened #52 which fixes the issue with compilation errors, at least the majority of them.
2. I checked again. Order of test runs and their appearance in the `tests` array should be deterministic and follow the order of definition in the test file. If this is not true, I need some more info to reproduce the issue.

**Comment by ErikSchierboom** [comment]
I'll double check about the order. Might be some silly mistake of mine

**Comment by ErikSchierboom** [comment]
@NobbZ I've rebased and CI is now green

**Review by NobbZ — APPROVED** [review]
LGTM.

Though I am curious why you have a `expected_results.json` and a `results.json` per test, which on a cursory glance have the same contents.

**Comment by ErikSchierboom** [comment]
> Though I am curious why you have a expected_results.json and a results.json per test, which on a cursory glance have the same contents.

Because I forgot to update the `.gitignore` file 🤦  I've fixed this. Thanks for catching that!

**Pull request merged**
