### PR TITLE
Prepare runner

### PR DESCRIPTION
**Pull request by NobbZ**

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
The aliases used in the Dockerfile must be lowercase according to my Docker installation (v20):

> failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to parse stage name "ERLANG": invalid reference format: repository name must be lowercase

**Comment by ErikSchierboom** [comment]
> And thanks for the vim-script-runner link. I'm already doing something similar in my test-suite:
> https://github.com/NobbZ/erlang-test-runner/blob/main/test/runs_in_docker_SUITE.erl#L213-L224

That's cool. It does mean that one has to have Erlang installed locally to run the test runner, whereas https://github.com/exercism/vimscript-test-runner/blob/main/bin/run-in-docker.sh doesn't even need Erlang to be installed to run 🤷

**Comment by ErikSchierboom** [comment]
> Re the error you are facing now, if I understand my code correctly, this means that there is an src/example.erl in the input and the runner searches for the corresponding test module, alternatively, you have an src/hello_world.erl which first line is -module(example). (or something semantically equivalent).

This was indeed a mistake on my part. I just noticed that the exercises in the `test/runs_tests_SUITE_data` directory don't have a `.erl` extension, which I failed to notice. The test runner is working correctly!

**Comment by ErikSchierboom** [comment]
One final remark regarding the `results.json` file. We've recently updated the [test runner interface specification](https://github.com/exercism/docs/blob/main/building/tooling/test-runners/interface.md) to allow for two types of test runners, identified via a new `version` property in the `results.json` file (see [the spec for the version property](https://github.com/exercism/docs/blob/main/building/tooling/test-runners/interface.md#version)):

1. `version: 1` test runners are quite basic, and only detect if either all tests passed or not. These test runners capture the console output of the test runner and output that. They do _not_ include details on individual tests passing/failing
2. `version: 2` test runners contain detailed information on individual tests passing/failing. We've recently added a required field named `test_code`, which contains the code the test ran to verify the behavior (see [the spec for the test_code property](https://github.com/exercism/docs/blob/main/building/tooling/test-runners/interface.md#test-code)).

The test runner's output is currently what I refer to as version 1.5: it contains the individual test information, but does not yet contain the `test_code` key. If possible, the test runner should be updated to also include the test code, in which case the `version` property should also be added with `2` as its value.

You are completely free on how you want to extract the test code, either via the AST or via finding the test code in the source code text via string manipulation. 

Let me know if there are any questions.

**Comment by NobbZ** [comment]
> It does mean that one has to have Erlang installed locally to run the test runner

Yes, that is a requirement anyway, runtime needs to be available.

Or do you mean to run the testsuite? Well, yes, this is also true (currently), I might be able to wrap that in docker, though it wouldn't be as nicely integrated testing experience (for those who are used to common test).

> I just noticed that the exercises in the test/runs_tests_SUITE_data directory don't have a .erl extension, which I failed to notice. The test runner is working correctly!

Yes, this is sadly a restriction in the build system that is often reported as a bug but not yet solved.

> The test runner's output is currently what I refer to as version 1.5: it contains the individual test information, but does not yet contain the test_code key. If possible, the test runner should be updated to also include the test code, in which case the version property should also be added with 2 as its value.

Yes, I am aware, though I wanted to have the actual runner functional before tackling the `test_code` field.

Using some pretty printed AST to get the failed test is probably no problem for generated tests, as they follow an exact pattern, though more problematic are some hand written suites that use advanced features like lazy test generation at run time. I have to decide how exactly to deal with them.

For normal tests I have a function name that I can just ask the module in memory for the corresponding debug symbols which are basically enriched AST.

The lazily generated though do not have a straight one to one mapping from test- to function name, instead there can be many tests in a single function.

Though currently I am indeed considering rewriting the 4 exercises tests to not use the advanced features as that will make many things easier.

**Comment by ErikSchierboom** [comment]
> Or do you mean to run the testsuite? Well, yes, this is also true (currently), I might be able to wrap that in docker, though it wouldn't be as nicely integrated testing experience (for those who are used to common test).

I meant both the test suite and the one-off test run. But it is just a minor suggestion that you can completely ignore :)

> Yes, I am aware, though I wanted to have the actual runner functional before tackling the test_code field.
> 
> Using some pretty printed AST to get the failed test is probably no problem for generated tests, as they follow an exact pattern, though more problematic are some hand written suites that use advanced features like lazy test generation at run time. I have to decide how exactly to deal with them.
> 
> For normal tests I have a function name that I can just ask the module in memory for the corresponding debug symbols which are basically enriched AST.
>
>The lazily generated though do not have a straight one to one mapping from test- to function name, instead there can be many tests in a single function.
>
>Though currently I am indeed considering rewriting the 4 exercises tests to not use the advanced features as that will make many things easier.

Makes sense. I'd probably suggest merging this before you take on the test code bit, as then we'll have an almost fully working test runner instead of having no test runner at all. Let me know what you think.

**Comment by ErikSchierboom** [comment]
>I'd probably suggest merging this before you take on the test code bit, as then we'll have an almost fully working test runner instead of having no test runner at all. Let me know what you think.

@NobbZ Small bump regarding the above question :)

**Comment by NobbZ** [comment]
Then I think lets merge it, and I will continue to make it work after that.

Though a review by @exercism/maintainers-admin is required.

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
@NobbZ The honor is all yours!

**Pull request merged**
