### PR TITLE
Optimise docker image size and update erlang

### PR DESCRIPTION
**Pull request by NobbZ**
Follow-Up to #48 by @meatball133

### CODE REVIEW

**Comment by NobbZ** [comment]
PS:

```
$ docker image inspect alpine | jq '.[].Size' | numfmt --to-unit=Mi --format='%.2f MiB'
56.60 MiB
$ docker image inspect main | jq '.[].Size' | numfmt --to-unit=Mi --format='%.2f MiB'
164.22 MiB
```

To compare the sizes before and after the change in the Dockerfile.

**Comment by NobbZ** [comment]
PPS: I am also aware of a completely different way to build the base image, and I would expect that the size cut in half another time.

This way is quite different to running a `docker build` on a `Dockerfile` though, and it might be unbearable for the admin team to review.

I will try to apply that technique later today just to get a feeling for the resulting image size.

**Comment by NobbZ** [comment]
Scratch the last one, with erlang it isn't as easy as with elixir. I will definitely need to dig much deeper, and I do not think it is worth the time right now.

Image sizes around 50 to 60 MiB are already quite good.

**Review by ErikSchierboom — APPROVED** [review]
Nice!

**Pull request merged**
